export const EventTypes = {
    ALL_NODE: "ALL_NODE",
    ONE_FROM_ALL: "ONE_FROM_ALL",
    HTTP_RESPONSE: 'HTTP_RESPONSE',
    AUTH_RESULT: 'AUTH_RESULT',
    EMAIL_RESPONSE: 'EMAIL_RESPONSE',
    AZURE_AD_USER_LIST_RESPONSE: "AZURE_AD_USER_LIST_RESPONSE",
}